log: updated frem

diff --git a/tools/frem b/tools/frem
--- a/tools/frem
+++ b/tools/frem
@@ -4,7 +4,14 @@
 # Stands for "flush reminders"
 # Serves a really specific purpose of just clearing my reminders file
 
-reminders="$HOME/.local/zsh/zsh_reminders"
+reminders="$HOME/.reminders"
 
-echo "" > "$reminders"
-exit 0
+if [ -f "$reminders" ]; then
+    echo "" > "$reminders"
+    exit 0
+else
+    echo "[$0] File $reminders not found."
+    exit 1
+fi
+
+exit 2
