log: added flags to hashcmp (verbose and nocolor)

diff --git a/tools/hashcmp b/tools/hashcmp
--- a/tools/hashcmp
+++ b/tools/hashcmp
@@ -10,15 +10,47 @@
 RED="\e[1;31m"
 GREEN="\e[1;32m"
 NORMAL="\e[0m"
+PN="$(basename $0)"
+
+# flags
+verbose=0
 
 argc=$#
-files=("$@")
+declare -a files
 
 # Error if two or less argcs
 if (( argc < 2 )); then
-    echo -e "${RED}[$0] ERROR: Argument count is less than 2.${NORMAL}"
+    echo -e "${PNERR} Argument count is less than 2."
     exit -1
 fi
+
+for arg in "$@"; do
+    if [[ "${arg:0:1}" != "-" ]]; then
+        files+=("$arg")
+        continue
+    fi
+
+    for ((i=1; i<${#arg}; i++)); do
+        case ${arg:i:1} in
+            "v") verbose=1 ;;
+            "n") 
+                RED=""
+                GREEN=""
+                ;;
+            *) 
+                echo -e "${PNERR} ${letter}: Flag not found"
+                exit
+                ;;
+        esac
+    done
+done
+
+ERR="${RED}error:${NORMAL}"
+PNERR="${PN}: ${ERR}"
+FAILED="${RED}failed${NORMAL}"
+OK="${GREEN}OK${NORMAL}"
+
+unset letter flagNotFound
 
 
 # An array containing filenames as keys and hashes as values
@@ -27,8 +59,13 @@ index=0
 for file in "${files[@]}"; do
     
     # Check if files exist
+    if [ ! -e "$file" ]; then
+        echo -e "${PNERR} '$file': No such file or directory"
+        exit -1
+    fi
+
     if [ ! -f "$file" ]; then
-        echo "[$0] Cannot find file '$file'."
+        echo -e "${PNERR} '$file': Not a file"
         exit -1
     fi
 
@@ -37,27 +74,22 @@ for file in "${files[@]}"; do
 done
 
 # Compare each hash file with the first one given
-echo "Checking each file against file '${files[0]}'"...
-failed=false
+ret=0
 count=0
 for (( i = 1; i < ${#hashes[@]}; i++ )); do
 
     if [[ "${hashes[0]}" != "${hashes[$i]}" ]]; then
-        echo -e "${RED}${files[$i]}: FAILED${NORMAL}"
-        failed=true
+        echo -e "${files[$i]}: $FAILED"
+        ret=1
         count=$((count+1))
-
-    else echo -e "${GREEN}${files[$i]}: OK${NORMAL}"
+    else 
+        echo -e "${files[$i]}: $OK"
     fi
 done
 
-echo ""
-echo -e "[$0] result: $count file/s failed."
-if [[ $failed == true ]]; then
-    exit 1
-
-else exit 0
+if [ $verbose -eq 1 ]; then
+    echo ""
+    echo -e "${PN}: result: $count file/s failed."
 fi
 
-echo -e "${RED}Unknown error occured.${NORMAL}"
-exit 1
+exit $ret
