log: reminders: cleaned up add()

diff --git a/tools/reminders b/tools/reminders
--- a/tools/reminders
+++ b/tools/reminders
@@ -2,20 +2,26 @@
 
 reminders_file="$HOME/.reminders"
 PN="$(basename $0)"
+RED="\e[1;31m"
+GREEN="\e[1;32m"
+YELLOW="\e[1;33m"
+NC="\e[0m"
+ERROR="${RED}error${NC}"
+WARNING="${YELLOW}warning${YELLOW}"
 
 _add() {
     if [ -z "$1" ]; then
-        echo "$PN: $0: missing input"
+        echo -e "$PN: $ERROR: $0: missing input" >&2
         return 1
     fi
 
-    echo "[ ] $1" >> $reminders_file
+    echo "[ ] $1" >> "$reminders_file"
     return $?
 }
 
 _clear() {
     local tmpfile="$(mktemp)"
-    echo "$PN: making copy to $tmpfile"
+    echo "$PN: info: making copy to $tmpfile"
 
     if [ "$1" == "all" ]; then
         if [ ! -s "$reminders_file" ]; then
