log: reminders: fixed backing up logic in clear; also made errors pipe to stderr

diff --git a/tools/reminders b/tools/reminders
--- a/tools/reminders
+++ b/tools/reminders
@@ -24,17 +24,21 @@ _clear() {
     echo "$PN: info: making copy to $tmpfile"
 
     if [ "$1" == "all" ]; then
-        if [ ! -s "$reminders_file" ]; then
-            cat "$reminders_file" > "$tmpfile"
+        if [ -s "$reminders_file" ]; then
+            cp "$reminders_file" "$tmpfile"
         fi
 
-        echo "$PN: clearing $reminders_file"
+        echo "$PN: info: clearing $reminders_file"
         echo -n "" > $reminders_file
 
         return 0
     fi
 
     local line="$1"
+    if [[ ! "$line" =~ ^[[:digit:]]*$ ]]; then
+        echo -e "$PN: $ERROR: $0: must be a task number" >&2
+        return 1
+    fi
 
     sed -n "${line}p" "$reminders_file" | tee -a "$tmpfile"
     sed -i "${line}d" "$reminders_file"
@@ -44,7 +48,7 @@ _clear() {
 _uncomplete() {
     if [[ "$1" == "all" ]]; then
         if [ $# -gt 2 ]; then
-            echo "$PN: $0: too many arguments"
+            echo -e "$PN: $ERROR: $0: too many arguments" >&2
             return 1
         fi
 
@@ -53,6 +57,10 @@ _uncomplete() {
     fi
 
     local line="$1"
+    if [[ ! "$line" =~ ^[[:digit:]]*$ ]]; then
+        echo -e "$PN: $ERROR: $0: must be a task number" >&2
+        return 1
+    fi
 
     sed -i "${line}s/\[\*\]/[ ]/" "$reminders_file"
     [ $? -eq 0 ] || return 1
@@ -64,7 +72,7 @@ _uncomplete() {
 _complete() {
     if [ "$1" == "all" ]; then
         if [ $# -gt 2 ]; then
-            echo "$PN: $0: too many arguments"
+            echo -e "$PN: $ERROR: $0: too many arguments" >&2
             return 1
         fi
 
@@ -73,6 +81,10 @@ _complete() {
     fi
 
     local line="$1"
+    if [[ ! "$line" =~ ^[[:digit:]]*$ ]]; then
+        echo -e "$PN: $ERROR: $0: must be a task number" >&2
+        return 1
+    fi
 
     sed -i "${line}s/\[ \]/[*]/" "$reminders_file"
     [ $? -eq 0 ] || return 1
@@ -124,7 +136,7 @@ _ls() {
 
 if [ ! -f "$reminders_file" ]; then
     if ! touch "$reminders_file"; then
-        echo "$PN: error: $reminders_file: unable to create file"
+        echo -e "$PN: $ERROR: $reminders_file: unable to create file" >&2
         exit 1
     fi
 fi
@@ -132,7 +144,7 @@ fi
 case $1 in
     "add")
         if [ $# -lt 2 ]; then
-            echo "$PN: add: too few arguments"
+            echo -e "$PN: $ERROR: add: too few arguments" >&2
             exit 1
         fi
 
@@ -160,7 +172,7 @@ case $1 in
         ;;
     "complete")
         if [ $# -lt 2 ]; then
-            echo "$PN: complete: too few arguments"
+            echo -e "$PN: $ERROR: complete: too few arguments" >&2
             exit 1
         fi
 
@@ -170,7 +182,7 @@ case $1 in
         ;;
     "uncomplete")
         if [ $# -lt 2 ]; then
-            echo "$PN: uncomplete: too few arguments"
+            echo -e "$PN: $ERROR: uncomplete: too few arguments" >&2
             exit 1
         fi
 
@@ -179,7 +191,7 @@ case $1 in
         done
         ;;
     *)
-        echo "$PN: error: $1: invalid subcommand"
+        echo -e "$PN: $ERROR: $1: invalid subcommand" >&2
         exit 1
         ;;
 esac
